# Stock name-to-ticker mapping
stock_mapping = {
    "3M": "MMM",
    "A. O. Smith": "AOS",
    "Abbott Laboratories": "ABT",
    "AbbVie": "ABBV",
    "Accenture": "ACN",
    "Adobe Inc.": "ADBE",
    "Advanced Micro Devices": "AMD",
    "AES Corporation": "AES",
    "Aflac": "AFL",
    "Agilent Technologies": "A",
    "Air Products": "APD",
    "Akamai Technologies": "AKAM",
    "Alaska Air Group": "ALK",
    "Albemarle Corporation": "ALB",
    "Alexandria Real Estate Equities": "ARE",
    "Align Technology": "ALGN",
    "Allegion": "ALLE",
    "Alliant Energy": "LNT",
    "Allstate": "ALL",
    "Alphabet Inc. (Class A)": "GOOGL",
    "Alphabet Inc. (Class C)": "GOOG",
    "Altria": "MO",
    "Amazon": "AMZN",
    "Amcor": "AMCR",
    "Ameren": "AEE",
    "American Airlines Group": "AAL",
    "American Electric Power": "AEP",
    "American Express": "AXP",
    "American International Group": "AIG",
    "American Tower": "AMT",
    "American Water Works": "AWK",
    "Ameriprise Financial": "AMP",
    "AmerisourceBergen": "ABC",
    "Ametek": "AME",
    "Amgen": "AMGN",
    "Amphenol": "APH",
    "Analog Devices": "ADI",
    "Ansys": "ANSS",
    "Aon": "AON",
    "APA Corporation": "APA",
    "Apple Inc.": "AAPL",
    "Applovin": "APP",
    "Applied Materials": "AMAT",
    "Aptiv": "APTV",
    "Arch Capital Group": "ACGL",
    "Archer-Daniels-Midland": "ADM",
    "Arista Networks": "ANET",
    "Arthur J. Gallagher & Co.": "AJG",
    "Assurant": "AIZ",
    "AT&T": "T",
    "Atmos Energy": "ATO",
    "Autodesk": "ADSK",
    "AutoZone": "AZO",
    "AvalonBay Communities": "AVB",
    "Avery Dennison": "AVY",
    "Baker Hughes": "BKR",
    "Ball Corporation": "BALL",
    "Bank of America": "BAC",
    "Bank of New York Mellon": "BK",
    "Baxter International": "BAX",
    "Becton, Dickinson and Company": "BDX",
    "Berkshire Hathaway": "BRK.B",
    "Best Buy": "BBY",
    "Bio-Rad": "BIO",
    "Bio-Techne": "TECH",
    "Biogen": "BIIB",
    "BlackRock": "BLK",
    "Boeing": "BA",
    "Booking Holdings": "BKNG",
    "BorgWarner": "BWA",
    "Boston Properties": "BXP",
    "Boston Scientific": "BSX",
    "Bristol-Myers Squibb": "BMY",
    "Broadcom Inc.": "AVGO",
    "Broadridge Financial Solutions": "BR",
    "Brown & Brown": "BRO",
    "Brown–Forman": "BF.B",
    "C.H. Robinson": "CHRW",
    "Cadence Design Systems": "CDNS",
    "Caesars Entertainment": "CZR",
    "Camden Property Trust": "CPT",
    "Campbell Soup Company": "CPB",
    "Capital One": "COF",
    "Cardinal Health": "CAH",
    "CarMax": "KMX",
    "Carnival Corporation": "CCL",
    "Carrier Global": "CARR",
    "Catalent": "CTLT",
    "Caterpillar Inc.": "CAT",
    "Cboe Global Markets": "CBOE",
    "CBRE Group": "CBRE",
    "CDW": "CDW",
    "Celanese": "CE",
    "Centene Corporation": "CNC",
    "CenterPoint Energy": "CNP",
    "Ceridian": "CDAY",
    "CF Industries": "CF",
    "Charles River Laboratories": "CRL",
    "Charles Schwab Corporation": "SCHW",
    "Charter Communications": "CHTR",
    "Chevron Corporation": "CVX",
    "Chipotle Mexican Grill": "CMG",
    "Chubb Limited": "CB",
    "Church & Dwight": "CHD",
    "Cigna": "CI",
    "Cincinnati Financial": "CINF",
    "Cintas": "CTAS",
    "Cisco": "CSCO",
    "Citigroup": "C",
    "Citizens Financial Group": "CFG",
    "Clorox": "CLX",
    "CME Group": "CME",
    "CMS Energy": "CMS",
    "CNA Financial": "CNA",
    "Cognizant": "CTSH",
    "Colgate-Palmolive": "CL",
    "Comcast": "CMCSA",
    "Comerica": "CMA",
    "Conagra Brands": "CAG",
    "ConocoPhillips": "COP",
    "Consolidated Edison": "ED",
    "Constellation Brands": "STZ",
    "Constellation Energy": "CEG",
    "CooperCompanies": "COO",
    "Copart": "CPRT",
    "Corning Inc.": "GLW",
    "Corteva": "CTVA",
    "Costco": "COST",
    "Coterra": "CTRA",
    "Crown Castle": "CCI",
    "CSX": "CSX",
    "Cummins": "CMI",
    "CVS Health": "CVS",
    "D.R. Horton": "DHI",
    "Danaher Corporation": "DHR",
    "Darden Restaurants": "DRI",
    "DaVita Inc.": "DVA",
    "Deere & Company": "DE",
    "Delta Air Lines": "DAL",
    "Dentsply Sirona": "XRAY",
    "Devon Energy": "DVN",
    "Dexcom": "DXCM",
    "Diamondback Energy": "FANG",
    "Digital Realty": "DLR",
    "Discover Financial": "DFS",
    "Dish Network": "DISH",
    "Disney": "DIS",
    "Dollar General": "DG",
    "Dollar Tree": "DLTR",
    "Dominion Energy": "D",
    "Domino's Pizza": "DPZ",
    "Dover Corporation": "DOV",
    "Dow Inc.": "DOW",
    "DTE Energy": "DTE",
    "Duke Energy": "DUK",
    "DuPont de Nemours": "DD",
    "DXC Technology": "DXC",
    "Eastman Chemical Company": "EMN",
    "Eaton Corporation": "ETN",
    "eBay": "EBAY",
    "Ecolab": "ECL",
    "Edison International": "EIX",
    "Edwards Lifesciences": "EW",
    "Electronic Arts": "EA",
    "Elevance Health": "ELV",
    "Emerson Electric": "EMR",
    "Enphase Energy": "ENPH",
    "Entergy": "ETR",
    "EOG Resources": "EOG",
    "EQT Corporation": "EQT",
    "Equifax": "EFX",
    "Equinix": "EQIX",
    "Equity Residential": "EQR",
    "Essex Property Trust": "ESS",
    "Everest Re": "RE",
    "Evergy": "EVRG",
    "Everest Re Group": "RE",
    "Eversource Energy": "ES",
    "Exelon": "EXC",
    "Expedia Group": "EXPE",
    "Expeditors International": "EXPD",
    "Extra Space Storage": "EXR",
    "ExxonMobil": "XOM",
    "F5 Networks": "FFIV",
    "Fastenal": "FAST",
    "Federal Realty Investment Trust": "FRT",
    "FedEx": "FDX",
    "Fifth Third Bancorp": "FITB",
    "First Republic Bank": "FRC",
    "First Solar": "FSLR",
    "FirstEnergy": "FE",
    "FleetCor Technologies": "FLT",
    "Ford Motor Company": "F",
    "Fortinet": "FTNT",
    "Fortive": "FTV",
    "Franklin Resources": "BEN",
    "Freeport-McMoRan": "FCX",
    "Garmin": "GRMN",
    "Generac": "GNRC",
    "General Dynamics": "GD",
    "General Electric": "GE",
    "General Motors": "GM",
    "Gilead Sciences": "GILD",
    "Globe Life": "GL",
    "Goldman Sachs": "GS",
    "Halliburton": "HAL",
    "Hartford Financial Services": "HIG",
    "Hasbro": "HAS",
    "HCA Healthcare": "HCA",
    "Healthpeak Properties": "PEAK",
    "Henry Schein": "HSIC",
    "Hershey": "HSY",
    "Hewlett Packard Enterprise": "HPE",
    "Hilton Worldwide": "HLT",
    "Hologic": "HOLX",
    "Home Depot": "HD",
    "Honeywell": "HON",
    "Hormel Foods": "HRL",
    "Host Hotels & Resorts": "HST",
    "Howmet Aerospace": "HWM",
    "Humana": "HUM",
    "Huntington Bancshares": "HBAN",
    "Huntington Ingalls Industries": "HII",
    "IDEX Corporation": "IEX",
    "Illinois Tool Works": "ITW",
    "Illumina": "ILMN",
    "Incyte": "INCY",
    "Ingersoll Rand": "IR",
    "Intel": "INTC",
    "Intercontinental Exchange": "ICE",
    "International Flavors & Fragrances": "IFF",
    "International Paper": "IP",
    "Interpublic Group": "IPG",
    "Intuit": "INTU",
    "Intuitive Surgical": "ISRG",
    "Iron Mountain": "IRM",
    "J.B. Hunt Transport Services": "JBHT",
    "Jack Henry & Associates": "JKHY",
    "Jacobs Engineering": "J",
    "Johnson & Johnson": "JNJ",
    "Johnson Controls": "JCI",
    "JPMorgan Chase": "JPM",
    "Juniper Networks": "JNPR",
    "Kellogg's": "K",
    "KeyCorp": "KEY",
    "Keysight Technologies": "KEYS",
    "Kimberly-Clark": "KMB",
    "Kraft Heinz": "KHC",
    "Kroger": "KR",
    "L3Harris Technologies": "LHX",
    "Labcorp": "LH",
    "Lam Research": "LRCX",
    "Las Vegas Sands": "LVS",
    "Lennar": "LEN",
    "Lilly (Eli) & Co.": "LLY",
    "Lincoln National": "LNC",
    "Linde plc": "LIN",
    "Live Nation Entertainment": "LYV",
    "LKQ Corporation": "LKQ",
    "Lockheed Martin": "LMT",
    "Loews Corporation": "L",
    "Lowe's": "LOW",
    "Lumen Technologies": "LUMN",
    "LyondellBasell": "LYB",
    "M&T Bank": "MTB",
    "Marathon Oil": "MRO",
    "Marathon Petroleum": "MPC",
    "Marriott International": "MAR",
    "Marsh McLennan": "MMC",
    "Masco": "MAS",
    "Mastercard": "MA",
    "McCormick & Company": "MKC",
    "McDonald's": "MCD",
    "McKesson": "MCK",
    "Medtronic": "MDT",
    "Merck & Co.": "MRK",
    "Meta Platforms": "META",
    "MetLife": "MET",
    "Microchip Technology": "MCHP",
    "Micron Technology": "MU",
    "Microsoft": "MSFT",
    "Mid-America Apartment Communities": "MAA",
    "Moderna": "MRNA",
    "Mohawk Industries": "MHK",
    "Molson Coors Beverage Company": "TAP",
    "Monolithic Power Systems": "MPWR",
    "Monster Beverage": "MNST",
    "Moody's Corporation": "MCO",
    "Morgan Stanley": "MS",
    "Mosaic Company": "MOS",
    "Motorola Solutions": "MSI",
    "Nasdaq, Inc.": "NDAQ",
    "National Oilwell Varco": "NOV",
    "Netflix": "NFLX",
    "Newmont Corporation": "NEM",
    "News Corp": "NWSA",
    "NextEra Energy": "NEE",
    "Nike": "NKE",
    "Norfolk Southern": "NSC",
    "Northern Trust": "NTRS",
    "Northrop Grumman": "NOC",
    "NortonLifeLock": "NLOK",
    "NVIDIA": "NVDA",
    "NVR, Inc.": "NVR",
    "Occidental Petroleum": "OXY",
    "Old Dominion Freight Line": "ODFL",
    "Omnicom Group": "OMC",
    "Oracle": "ORCL",
    "O'Reilly Automotive": "ORLY",
    "Paccar": "PCAR",
    "Paychex": "PAYX",
    "Paycom": "PAYC",
    "PayPal": "PYPL",
    "PepsiCo": "PEP",
    "Pfizer": "PFE",
    "Philip Morris International": "PM",
    "Phillips 66": "PSX",
    "Pioneer Natural Resources": "PXD",
    "PNC Financial Services": "PNC",
    "PPL Corporation": "PPL",
    "Prudential Financial": "PRU",
    "Public Storage": "PSA",
    "PulteGroup": "PHM",
    "PVH Corp.": "PVH",
    "Qualcomm": "QCOM",
    "Quanta Services": "PWR"
}

def get_stock_ticker(search_query):
    """
    Get the ticker symbol for a stock based on a search query.
    
    Args:
    search_query (str): The stock name or partial name to search for.
    
    Returns:
    str: The ticker symbol for the selected stock, or None if no match is found.
    """
    search_query = search_query.strip().title()
    filtered_stocks = [name for name in stock_mapping.keys() if search_query in name]
    
    if filtered_stocks:
        return stock_mapping[filtered_stocks[0]]  # Return the first match
    else:
        return None
    
def get_stock_suggestions(search_query):
    """
    Get a list of stock names that match the search query.
    
    Args:
    search_query (str): The stock name or partial name to search for.
    
    Returns:
    list: A list of matching stock names.
    """
    search_query = search_query.strip().title()
    return [name for name in stock_mapping.keys() if search_query in name]